.TH mdt 1 "Nov 21, 2005"  
.SH NAME
mdt \- Useful scripts for combining and comparing Debian derivatives
.SH SYNOPSIS
\fBmdt\fR [OPTIONS] [COMMAND]
.SH DESCRIPTION
mdt is the entry point for MultiDistroTools (mdt
stands for MultiDistroTools). MultiDistroTools provides some useful scripts
allowing to generate and combine package lists and retrieve information from
them. It aims at automating all the tasks that most MOTUs, for example, have
to do on a regular basis. 
.PP
Run mdt without argument to get inline help.
.TP 
\fB\-V\fR, \fB\-\-version\fR 
Show version information.
.TP 
\fB\-v\fR, \fB\-\-verbose\fR 
Run in verbose mode.
.TP 
\fB\-h\fR, \fB\-\-help \fIcommand\fB\fR 
Without argument, lists all available commands and
their summaries. With argument, shows some help for the given
command.
.SH "SEE ALSO"
Homepage : 
https://wiki.ubuntu.com/MultiDistroTools
.SH AUTHOR
Copyright (C) 2005 Lucas Nussbaum lucas@lucas\-nussbaum.net
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version.
.PP
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
more details.
